services:
  - type: web
    name: remote-desktop-server
    env: python
    runtime: python-3.11.9
    plan: professional
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: 1
